#!/bin/bash

source /etc/lsb-release
. $HOME/.config/wayland-build-tools/wl_defines.sh

sudo apt-get update
sudo apt-get -y install git cmake gcc wget

# generic build dependencies for ubuntu
sudo apt-get -y install autoconf automake bison debhelper dpkg-dev flex libtool
sudo apt-get -y install pkg-config quilt python-libxml2

# libinput needs meson
if [ "$DISTRIB_CODENAME" = "xenial" ]; then
	# Xenial (16.04) has a too-old meson
	# So need to install from security.ubuntu.com
	sudo apt-get -y install ninja-build
	sudo apt-get -y install meson
else
    sudo apt-get -y install python3-pip
    sudo apt-get -y install python3-libevdev
    pip3 install "meson>=0.54.0" ninja mako --user
    pip3 install pyudev pytest --user
    pip3 install sphinx recommonmark sphinx_rtd_theme --user
fi

# wayland/weston specific stuff
sudo apt-get -y install xmlto
sudo apt-get -y install doxygen
sudo apt-get -y install graphviz
sudo apt-get -y install linux-libc-dev
sudo apt-get -y install libexpat1-dev
sudo apt-get -y install libmtdev-dev
sudo apt-get -y install libpam0g-dev
sudo apt-get -y install libunwind8-dev
sudo apt-get -y install libpciaccess-dev
sudo apt-get -y install libudev-dev
sudo apt-get -y install libgudev-1.0-dev
sudo apt-get -y install libdbus-1-dev
sudo apt-get -y install libva-dev
sudo apt-get -y install freerdp2-dev
sudo apt-get -y install liblcms2-dev
sudo apt-get -y install libcolord-dev
sudo apt-get -y install llvm-dev
sudo apt-get -y install libelf-dev
sudo apt-get -y install libxrandr-dev
sudo apt-get -y install libxml2-dev
sudo apt-get -y install libpng-dev
sudo apt-get -y install libjpeg-dev
sudo apt-get -y install libwebp-dev
sudo apt-get -y install libsystemd-dev
sudo apt-get -y install libglib2.0-dev
sudo apt-get -y install libgcrypt20-dev
sudo apt-get -y install x11proto-scrnsaver-dev
sudo apt-get -y install libxfont-dev
sudo apt-get -y install libedit-dev
sudo apt-get -y install check

# xwayland specific stuff
if [ ${INCLUDE_XWAYLAND} ]; then
	sudo apt-get -y install libxcb-composite0-dev
	sudo apt-get -y install x11proto-randr-dev
	sudo apt-get -y install x11proto-composite-dev
	sudo apt-get -y install x11proto-xinerama-dev
	sudo apt-get -y install x11proto-dri2-dev
	sudo apt-get -y install x11proto-gl-dev
	sudo apt-get -y install xutils-dev
	sudo apt-get -y install libxcursor-dev
	#sudo apt-get -y install libdrm-dev
	sudo apt-get -y install libx11-dev
	sudo apt-get -y install libx11-xcb-dev
	#sudo apt-get -y install x11proto-dri3-dev
	sudo apt-get -y install libxdamage-dev
	sudo apt-get -y install libxext-dev
	sudo apt-get -y install libxfixes-dev
	sudo apt-get -y install libxxf86vm-dev
fi
